# Site Settings
title:               Millennial
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/Millennial"
url:                #"https://lenpaul.github.io"
github:
  url:               "https://lenpaul.github.io/Millennial"
author:
  name:              "Paul Le"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "lenpaul"
  facebook:          "Le.Paul.94"
  linkedin:          "lenpaul"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
