# Site Build Settings

# jekyll-paginate configuration
paginate:            50

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
future:              true

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Working with Digital Data"
description:	       "Working with Digital Data in Religious Studies (course website, summer semester 2024)"
author:              "Nathan Gibson"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

hide_related_posts: true
hide_post_share: true