# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate,jekyll-paginate-v2]

sass:
  sass_dir: assets/css
  style: :nested
