# Site Settings
baseurl:            #"/Millennial"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Millennial"

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
